name: Test website build ⚙️

on:
  pull_request:
    paths:
      - '**'

jobs:
  build:
    name: Test website build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install requirements 📦
        run: |
          python3 -m pip install --upgrade pip
          pip3 install zensical
      - name: Test build 📦
        run: zensical build --clean --strict
